/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.struts;

import org.apache.struts.action.ActionForm;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 03-29-2011
 *
 * XDoclet definition:
 *
 * @struts.form name="loginform"
 */
public class LoginForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	/** username property */
	private String username;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/**
	 * Returns the username.
	 *
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * Set the username.
	 *
	 * @param username
	 *            The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Returns the password.
	 *
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Set the password.
	 *
	 * @param password
	 *            The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}