/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.struts;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 03-29-2011
 *
 * XDoclet definition:
 *
 * @struts.action path="/login" name="loginform" input="/login.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="failure" path="/failure.jsp"
 * @struts.action-forward name="success" path="/index.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 *
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginform = (LoginForm) form;
		boolean flag = false;
		String rkey = "failure";
		String user = loginform.getUsername();
		String pwd = loginform.getPassword();
		LoginService service = new LoginService();
		flag = service.isAuthenticate(user, pwd);
		if (flag)
			rkey = "success";
		return mapping.findForward(rkey);
	}
}