-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--   at:        2014-02-06 18:29:28 GMT+05:30
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g




CREATE TABLE Actions
  (
    ActionID NUMBER NOT NULL ,
    ActionName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Actions ADD CONSTRAINT Action_PK PRIMARY KEY
(
  ActionID
)
;

CREATE TABLE AgentDetails
  (
    AgentID NUMBER NOT NULL ,
    AgentName NVARCHAR2 (50) ,
    IP NVARCHAR2 (20) ,
    Port NUMBER ,
    MachineDetails NVARCHAR2 (100) ,
    Protocol NVARCHAR2 (50) ,
    Status CHAR (1) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE AgentDetails ADD CONSTRAINT AgectDetails_PK PRIMARY KEY
(
  AgentID
)
;

CREATE TABLE AppFeature
  (
    FeatureID NUMBER NOT NULL ,
    FeatureName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    FunctionalID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE AppFeature ADD CONSTRAINT Feature_PK PRIMARY KEY
(
  FeatureID
)
;

CREATE TABLE AppFunctionality
  (
    FunctionalID NUMBER NOT NULL ,
    FunctionalName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    AppID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE AppFunctionality ADD CONSTRAINT Functional_PK PRIMARY KEY
(
  FunctionalID
)
;

CREATE TABLE Application
  (
    AppID NUMBER NOT NULL ,
    AppName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Application ADD CONSTRAINT APPLICATION_PK PRIMARY KEY
(
  AppID
)
;

CREATE TABLE CaseStepMapping
  (
    CaseStepMappingID INT NOT NULL ,
    TestCaseID INT NOT NULL ,
    TestStepID INT NOT NULL ,
    CreatedBy VARCHAR (100) ,
    CreatedDateTime DATE ,
    UpdatedBy VARCHAR (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE CaseStepMapping ADD CONSTRAINT CaseStepMapping_PK PRIMARY KEY
(
  CaseStepMappingID, TestCaseID, TestStepID
)
;

CREATE TABLE ConditionGroup
  (
    ConditionGroupID NUMBER NOT NULL ,
    ConditionGroupName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    AppID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ConditionGroup ADD CONSTRAINT ConditionGroup_PK PRIMARY KEY
(
  ConditionGroupID
)
;

CREATE TABLE Conditions
  (
    ConditionID NUMBER NOT NULL ,
    ConditionName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    Expression NVARCHAR2 (500) ,
    ConditionGroupID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Conditions ADD CONSTRAINT Condition_PK PRIMARY KEY
(
  ConditionID
)
;

CREATE TABLE GRX_DeviceID_Suffix
  (
    SuffixID NVARCHAR2 ,
    Suffix NVARCHAR2 (50) ,
    Active CHAR (1) ,
    COUNT  NUMBER
  ) ;

CREATE TABLE GenericData
  (
    ID NUMBER NOT NULL ,
    KeyName NVARCHAR2 (200) ,
    Value NVARCHAR2 (200) ,
    AppID NUMBER NOT NULL
  ) ;
ALTER TABLE GenericData ADD CONSTRAINT GenericData_PK PRIMARY KEY
(
  ID
)
;

CREATE TABLE IdentifierType
  (
    IdentifierTypeID NUMBER NOT NULL ,
    IdentifierTypeName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    AppID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE IdentifierType ADD CONSTRAINT IdentifierType_PK PRIMARY KEY
(
  IdentifierTypeID
)
;

CREATE TABLE LaneResults
  (
    LaneResultsID  NUMBER NOT NULL ,
    ScheduleLaneID NUMBER NOT NULL ,
    AgentID        NUMBER NOT NULL ,
    BuildVersion NVARCHAR2 (200) ,
    OS NVARCHAR2 (200) ,
    FailureDetails NVARCHAR2 (500) ,
    TestRunID           NUMBER NOT NULL ,
    Result              CHAR (1) ,
    StartDateTime       DATE ,
    EndDateTime         DATE ,
    PercentagePassCount NUMBER ,
    PercentageFailCount NUMBER
  ) ;
ALTER TABLE LaneResults ADD CONSTRAINT LaneResults_PK PRIMARY KEY
(
  LaneResultsID
)
;

CREATE TABLE ObjectGroup
  (
    ObjectGroupID NUMBER NOT NULL ,
    ObjectGroupName NVARCHAR2 (200) NOT NULL ,
    Description NVARCHAR2 (200) ,
    AppID    NUMBER NOT NULL ,
    ScreenID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ObjectGroup ADD CONSTRAINT ObjectGroup_PK PRIMARY KEY
(
  ObjectGroupID
)
;

CREATE TABLE ObjectType
  (
    ObjectTypeID NUMBER NOT NULL ,
    ObjectTypeName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    ActionId NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ObjectType ADD CONSTRAINT ObjectType_PK PRIMARY KEY
(
  ObjectTypeID
)
;

CREATE TABLE Objects
  (
    ObjectID NUMBER NOT NULL ,
    ObjectName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    ObjectGroupID    NUMBER NOT NULL ,
    ObjectTypeID     NUMBER NOT NULL ,
    IdentifierTypeID NUMBER NOT NULL ,
    AppID            NUMBER NOT NULL ,
    Identifier NVARCHAR2 (4000) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Objects ADD CONSTRAINT Objects_PK PRIMARY KEY
(
  ObjectID
)
;

CREATE TABLE Param
  (
    ParamID NUMBER NOT NULL ,
    ParamName NVARCHAR2 (200) ,
    Description NVARCHAR2 (200) ,
    SortOrder    NUMBER ,
    ParamGroupID NUMBER NOT NULL ,
    ObjectID     NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Param ADD CONSTRAINT Parameter_PK PRIMARY KEY
(
  ParamID
)
;

CREATE TABLE ParamGroup
  (
    ParamGroupID NUMBER NOT NULL ,
    ParamGroupName NVARCHAR2 (200) ,
    Description NVARCHAR2 (200) ,
    Tag NVARCHAR2 (50) ,
    AppID         NUMBER NOT NULL ,
    ObjectGroupID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_PK PRIMARY KEY
(
  ParamGroupID
)
;

CREATE TABLE PlanSuiteMapping
  (
    PlanSuiteMappingID NUMBER NOT NULL ,
    TestPlanID         NUMBER NOT NULL ,
    TestSuiteID        NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE PlanSuiteMapping ADD CONSTRAINT PlanSuiteMapping_PK PRIMARY KEY
(
  PlanSuiteMappingID, TestPlanID, TestSuiteID
)
;

CREATE TABLE Replacement_Strings
  (
    ID    NUMBER NOT NULL ,
    AppID NUMBER NOT NULL ,
    "Level" NVARCHAR2 (50) ,
    Foreign_ID NVARCHAR2 (50) ,
    Name NVARCHAR2 (500) ,
    Value NVARCHAR2 (500) ,
    ENCRYPTED NUMBER
  ) ;
ALTER TABLE Replacement_Strings ADD CONSTRAINT Replacement_Strings_PK PRIMARY KEY
(
  ID
)
;

CREATE TABLE Runner
  (
    RunnerID NUMBER NOT NULL ,
    RunnerName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Runner ADD CONSTRAINT Runner_PK PRIMARY KEY
(
  RunnerID
)
;

CREATE TABLE Runners_DeviceID_GEN
  (
    TableID NUMBER NOT NULL ,
    Type NVARCHAR2 (50) ,
    StartRange NUMBER ,
    EndRange   NUMBER ,
    DateAdded  DATE ,
    ExtraID NVARCHAR2 (50) ,
    Info NVARCHAR2 (100)
  ) ;
ALTER TABLE Runners_DeviceID_GEN ADD CONSTRAINT Runners_DeviceID_GEN_PK PRIMARY KEY
(
  TableID
)
;

CREATE TABLE ScenarioCaseMapping
  (
    ScenarioCaseMappingID NUMBER NOT NULL ,
    TestScenarioID        NUMBER NOT NULL ,
    TestCaseID            NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE ScenarioCaseMapping ADD CONSTRAINT ScenarioCaseMapping_PK PRIMARY KEY
(
  ScenarioCaseMappingID, TestScenarioID, TestCaseID
)
;

CREATE TABLE Scheduler
  (
    ScheduleID NUMBER NOT NULL ,
    SchedulerName NVARCHAR2 (500) ,
    TestPlanID   NUMBER NOT NULL ,
    TestDataID   NUMBER NOT NULL ,
    AgentID      NUMBER NOT NULL ,
    AppID        NUMBER NOT NULL ,
    ScheduleTime DATE ,
    Status       VARCHAR2 ,
    Frequency NVARCHAR2 (200) ,
    Notifications NVARCHAR2 (500) ,
    MultiLanes   CHAR (1) ,
    FailureCount NUMBER ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_PK PRIMARY KEY
(
  ScheduleID
)
;

CREATE TABLE SchedulerBackup
  (
    SchedulerbackupID NUMBER NOT NULL ,
    SchedulerName NVARCHAR2 (500) ,
    TestPlanID   NUMBER ,
    TestDataID   NUMBER ,
    AgentID      NUMBER ,
    AppID        NUMBER ,
    ScheduleTime DATE ,
    Status NVARCHAR2 ,
    Frequency NVARCHAR2 (200) ,
    Notifications NVARCHAR2 (500) ,
    MultiLanes   CHAR (1) ,
    FailureCount NUMBER ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE SchedulerBackup ADD CONSTRAINT SchedulerBackup_PK PRIMARY KEY
(
  SchedulerbackupID
)
;

CREATE TABLE SchedulerLaneDetails
  (
    ScheduleLaneID NUMBER NOT NULL ,
    LaneUserName NVARCHAR2 (50) ,
    ScheduleID NUMBER NOT NULL ,
    AgentID    NUMBER NOT NULL ,
    LaneType NVARCHAR2 (50) ,
    RunnerType NVARCHAR2 (100) ,
    Clones      NUMBER ,
    Iterations  NUMBER ,
    RampUpDelay NUMBER ,
    Duration    NUMBER ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE SchedulerLaneDetails ADD CONSTRAINT Lane_PK PRIMARY KEY
(
  ScheduleLaneID
)
;

CREATE TABLE SchedulerRunDetails
  (
    TestRunID           NUMBER NOT NULL ,
    TestPlanID          NUMBER NOT NULL ,
    TestDataID          NUMBER NOT NULL ,
    ScheduleID          NUMBER NOT NULL ,
    RunTime             DATE ,
    Result              CHAR (1) ,
    StartDateTime       DATE ,
    EndDateTime         DATE ,
    PercentagePassCount NUMBER ,
    PercentageFailCount NUMBER ,
    AppID               NUMBER NOT NULL
  ) ;
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT TestRunDetails_PK PRIMARY KEY
(
  TestRunID
)
;

CREATE TABLE Screen
  (
    ScreenID NUMBER NOT NULL ,
    ScreenName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    FeatureID NUMBER NOT NULL ,
    AppID     NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Screen ADD CONSTRAINT Screen_PK PRIMARY KEY
(
  ScreenID
)
;

CREATE TABLE SuiteScenarioMapping
  (
    SuiteScenarioMappingID NUMBER NOT NULL ,
    TestSuiteID            NUMBER NOT NULL ,
    TestScenarioID         NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
-- Error - Index SuiteScenarioMapping_TestPlan_FK has no columns
ALTER TABLE SuiteScenarioMapping ADD CONSTRAINT SuiteScenarioMapping_PK PRIMARY KEY
(
  SuiteScenarioMappingID, TestSuiteID, TestScenarioID
)
;

CREATE TABLE Task
  (
    TaskID NUMBER NOT NULL ,
    TaskName NVARCHAR2 (50) ,
    LaneID NUMBER NOT NULL ,
    TestPlanXlsPath NVARCHAR2 (200) ,
    DataSet NVARCHAR2 (50) ,
    RepeatNo NUMBER ,
    TagsToRun NVARCHAR2 (200) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE Task ADD CONSTRAINT Task_PK PRIMARY KEY
(
  TaskID
)
;

CREATE TABLE TaskResult
  (
    TaskResultID NUMBER NOT NULL ,
    TaskID       NUMBER NOT NULL ,
    LaneID       NUMBER NOT NULL ,
    RunResultID NVARCHAR2 (500) ,
    ReportFilePath NVARCHAR2 (500) ,
    TestRunID           NUMBER NOT NULL ,
    Result              CHAR (1) ,
    StartDateTime       DATE ,
    EndDateTime         DATE ,
    PercentagePassCount NUMBER ,
    PercentageFailCount NUMBER
  ) ;
-- Error - Index TaskResult_LaneResults_FK has no columns
ALTER TABLE TaskResult ADD CONSTRAINT TaskResult_PK PRIMARY KEY
(
  TaskResultID
)
;

CREATE TABLE TestCase
  (
    TestCaseID NUMBER NOT NULL ,
    CaseName NVARCHAR2 (500) ,
    Description NVARCHAR2 (200) ,
    ClassificationTag NVARCHAR2 (500) ,
    RunnerID         NUMBER NOT NULL ,
    ConditionGroupID NUMBER NOT NULL ,
    FunctionalID     NUMBER NOT NULL ,
    FeatureID        NUMBER NOT NULL ,
    Active           CHAR (1) ,
    Positive         CHAR (1) ,
    SortOrder        NUMBER ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestCase ADD CONSTRAINT TestCase_PK PRIMARY KEY
(
  TestCaseID
)
;

CREATE TABLE TestCaseResult
  (
    TestCaseResultID    NUMBER NOT NULL ,
    TestCaseID          NUMBER NOT NULL ,
    TestScenarioID      NUMBER NOT NULL ,
    TestRunID           NUMBER NOT NULL ,
    "Comment"           VARCHAR2 ,
    EXCEPTION           VARCHAR2 ,
    Request             VARCHAR2 ,
    Response            VARCHAR2 ,
    Result              NUMBER ,
    StartDateTime       DATE ,
    EndDateTime         DATE ,
    PercentagePassCount NUMBER ,
    PercentageFailCount NUMBER ,
    PercentageSkipCount NUMBER
  ) ;
--  ERROR: Index name length exceeds maximum allowed length(30)
CREATE INDEX TestCaseResult_TestScenarioResult_FK ON TestCaseResult
  (
    TestRunID ASC
  ) ;
ALTER TABLE TestCaseResult ADD CONSTRAINT TestCaseResult__IDX PRIMARY KEY
(
  TestCaseResultID
)
;

CREATE TABLE TestConditionData
  (
    TestConditionDataID NUMBER NOT NULL ,
    TestDataID          NUMBER NOT NULL ,
    ConditionGroupID    NUMBER NOT NULL ,
    ConditionID         NUMBER NOT NULL ,
    ConditionValue NVARCHAR2 (200) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
CREATE INDEX TestData_FK ON TestConditionData
  ( TestDataID ASC
  ) ;
CREATE INDEX TestCondition_FK ON TestConditionData
  ( ConditionID ASC
  ) ;
ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_PK PRIMARY KEY
(
  TestConditionDataID
)
;

CREATE TABLE TestData
  (
    TestDataID NUMBER NOT NULL ,
    AppID      NUMBER NOT NULL ,
    TestDataDescription NVARCHAR2 (200) ,
    Status VARCHAR2 ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestData ADD CONSTRAINT TestData_PK PRIMARY KEY
(
  TestDataID
)
;

CREATE TABLE TestParamData
  (
    TestParamDataID NUMBER NOT NULL ,
    ParamGroupID    NUMBER ,
    TestDataID      NUMBER NOT NULL ,
    ParamID         NUMBER NOT NULL ,
    ParamValue NVARCHAR2 (500) ,
    ValueBig NVARCHAR2 ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestParamData ADD CONSTRAINT TestParamData_PK PRIMARY KEY
(
  TestParamDataID
)
;

CREATE TABLE TestPlan
  (
    TestPlanID NUMBER NOT NULL ,
    PlanName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    AppID                NUMBER NOT NULL ,
    PreConditionGroupID  NUMBER NOT NULL ,
    PostConditionGroupID NUMBER NOT NULL ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_PK PRIMARY KEY
(
  TestPlanID
)
;

CREATE TABLE TestPlanResult
  (
    TestPlanResultID    NUMBER NOT NULL ,
    TestPlanRunName     VARCHAR2 ,
    TestPlanID          NUMBER NOT NULL ,
    TaskID              NUMBER NOT NULL ,
    TestRunID           NUMBER NOT NULL ,
    Result              CHAR (1) ,
    StartDateTime       DATE ,
    EndDateTime         DATE ,
    PercentagePassCount NUMBER ,
    PercentageFailCount NUMBER
  ) ;
-- Error - Index TestPlanResult_TaskResult_FK has no columns
ALTER TABLE TestPlanResult ADD CONSTRAINT TestPlanResult__IDX PRIMARY KEY
(
  TestPlanResultID
)
;

CREATE TABLE TestScenario
  (
    TestScenarioID NUMBER NOT NULL ,
    TestScenarioName NVARCHAR2 (500) ,
    Description NVARCHAR2 (500) ,
    AppID     NUMBER NOT NULL ,
    SortOrder NUMBER ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestScenario ADD CONSTRAINT TestScenario_PK PRIMARY KEY
(
  TestScenarioID
)
;

CREATE TABLE TestScenarioResult
  (
    TestScenarioResultID NUMBER NOT NULL ,
    TestScenarioID       NUMBER NOT NULL ,
    TestSuiteID          NUMBER NOT NULL ,
    TestRunID            NUMBER NOT NULL ,
    Result               CHAR (1) ,
    StartDateTime        DATE ,
    EndDateTime          DATE ,
    PercentagePassCount  NUMBER ,
    PercentageFailCount  NUMBER ,
    PercentageSkipCount  NUMBER
  ) ;
-- Error - Index TestScenarioResult_TestSuiteResult_FK has no columns
ALTER TABLE TestScenarioResult ADD CONSTRAINT TestScenarioResult_PK PRIMARY KEY
(
  TestScenarioResultID
)
;

CREATE TABLE TestStep
  (
    TestStepID NUMBER NOT NULL ,
    StepName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    TestStepType NVARCHAR2 (100) ,
    ActionID             NUMBER NOT NULL ,
    RunnerID             NUMBER NOT NULL ,
    InputParamGroupID    NUMBER NOT NULL ,
    OutputParamGroupID   NUMBER ,
    Active               CHAR (1) ,
    SortOrder            NUMBER ,
    PreConditionGroupID  NUMBER ,
    PostConditionGroupID NUMBER ,
    ExpectedResult NVARCHAR2 (50) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestStep ADD CONSTRAINT TestStep_PK PRIMARY KEY
(
  TestStepID
)
;

CREATE TABLE TestStepResult
  (
    TestStepResultID NUMBER NOT NULL ,
    TestStepID       NUMBER NOT NULL ,
    TestCaseID       NUMBER NOT NULL ,
    TestRunID        NUMBER NOT NULL ,
    "Comment" NVARCHAR2 (500) ,
    EXCEPTION NVARCHAR2 (500) ,
    Duration NUMBER ,
    Request NVARCHAR2 (500) ,
    Response NVARCHAR2 (500) ,
    Result        NUMBER ,
    StartDateTime DATE ,
    EndDateTime   DATE
  ) ;
--  ERROR: Index name length exceeds maximum allowed length(30)
CREATE INDEX TestStepResult_TestCaseResult_FK ON TestStepResult
  (
    TestCaseID ASC
  ) ;
ALTER TABLE TestStepResult ADD CONSTRAINT TestStepResult__IDX PRIMARY KEY
(
  TestStepResultID
)
;

CREATE TABLE TestSuite
  (
    TestSuiteID NUMBER NOT NULL ,
    SuiteName NVARCHAR2 (50) ,
    Description NVARCHAR2 (200) ,
    AppID     NUMBER NOT NULL ,
    SortOrder CHAR (1) ,
    CreatedBy NVARCHAR2 (100) ,
    CreatedDateTime DATE ,
    UpdatedBy NVARCHAR2 (100) ,
    UpdatedDateTime DATE
  ) ;
ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_PK PRIMARY KEY
(
  TestSuiteID
)
;

CREATE TABLE TestSuiteResult
  (
    TestSuiteResultID   NUMBER NOT NULL ,
    TestSuiteID         NUMBER NOT NULL ,
    TestPlanID          NUMBER NOT NULL ,
    TestRunID           NUMBER NOT NULL ,
    Result              CHAR (1) ,
    StartDateTime       DATE ,
    EndDateTime         DATE ,
    PercentagePassCount NUMBER ,
    PercentageFailCount NUMBER
  ) ;
-- Error - Index TestSuiteResult_TestPlanResult_FK has no columns
ALTER TABLE TestSuiteResult ADD CONSTRAINT TestSuiteResult__IDX PRIMARY KEY
(
  TestSuiteResultID
)
;

CREATE TABLE Test_Hits
  ( LogTime DATE , DeviceId NVARCHAR2 (50)
  ) ;

CREATE TABLE UsersApplicationMapping
  (
    UsersApplicationMappingID NUMBER NOT NULL ,
    USER_ID                   NUMBER NOT NULL ,
    AppID                     NUMBER NOT NULL ,
    AUTHORITY NVARCHAR2 (50)
  ) ;
ALTER TABLE UsersApplicationMapping ADD CONSTRAINT UsersApplicationMapping_PK PRIMARY KEY
(
  UsersApplicationMappingID
)
;

CREATE TABLE user_roles
  (
    USER_ROLE_ID NVARCHAR2 NOT NULL ,
    USER_ID NUMBER NOT NULL ,
    AUTHORITY NVARCHAR2 (50)
  ) ;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_PK PRIMARY KEY
(
  USER_ROLE_ID
)
;

CREATE TABLE users
  (
    USER_ID NUMBER NOT NULL ,
    USERNAME NVARCHAR2 (500) ,
    PASSWORD NVARCHAR2 (500) ,
    ENABLED NUMBER
  ) ;
ALTER TABLE users ADD CONSTRAINT Users_PK PRIMARY KEY
(
  USER_ID
)
;

ALTER TABLE AppFeature ADD CONSTRAINT AppFeature_Screen_FKv1 FOREIGN KEY ( FunctionalID ) REFERENCES AppFunctionality ( FunctionalID ) ON
DELETE CASCADE ;

ALTER TABLE TestPlan ADD CONSTRAINT AppID FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE CaseStepMapping ADD CONSTRAINT CaseStepMapping_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE CaseStepMapping ADD CONSTRAINT CaseStepMapping_TestStep FOREIGN KEY ( TestStepID ) REFERENCES TestStep ( TestStepID ) ;

ALTER TABLE ConditionGroup ADD CONSTRAINT ConditionGroup_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Conditions ADD CONSTRAINT Condition_ConditionGroup_FK FOREIGN KEY ( ConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE AppFunctionality ADD CONSTRAINT Functional_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ON
DELETE CASCADE ;

ALTER TABLE GenericData ADD CONSTRAINT GenericData_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE IdentifierType ADD CONSTRAINT IdentifierType_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE LaneResults ADD CONSTRAINT LaneResults_SchedulerRunDetails_FK FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

ALTER TABLE ObjectGroup ADD CONSTRAINT ObjectGroup_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ObjectGroup ADD CONSTRAINT ObjectGroup_Screen_FK FOREIGN KEY ( ScreenID ) REFERENCES Screen ( ScreenID ) ;

ALTER TABLE ObjectType ADD CONSTRAINT ObjectType_APPLICATION_FKv1 FOREIGN KEY ( ActionId ) REFERENCES Actions ( ActionID ) ;

ALTER TABLE Objects ADD CONSTRAINT Objects_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Objects ADD CONSTRAINT Objects_IdentifierType_FK FOREIGN KEY ( IdentifierTypeID ) REFERENCES IdentifierType ( IdentifierTypeID ) ;

ALTER TABLE Objects ADD CONSTRAINT Objects_ObjectGroup_FK FOREIGN KEY ( ObjectGroupID ) REFERENCES ObjectGroup ( ObjectGroupID ) ON
DELETE CASCADE ;

ALTER TABLE Objects ADD CONSTRAINT Objects_ObjectType_FK FOREIGN KEY ( ObjectTypeID ) REFERENCES ObjectType ( ObjectTypeID ) ;

ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE ParamGroup ADD CONSTRAINT ParamGroup_ObjectGroup_FK FOREIGN KEY ( ObjectGroupID ) REFERENCES ObjectGroup ( ObjectGroupID ) ;

ALTER TABLE Param ADD CONSTRAINT Parameter_Objects_FK FOREIGN KEY ( ObjectID ) REFERENCES Objects ( ObjectID ) ;

ALTER TABLE Param ADD CONSTRAINT Parameter_ParamGroup_FK FOREIGN KEY ( ParamGroupID ) REFERENCES ParamGroup ( ParamGroupID ) ON
DELETE CASCADE ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE Replacement_Strings ADD CONSTRAINT Replacement_Strings_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ScenarioCaseMapping ADD CONSTRAINT ScenarioCaseMapping_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE ScenarioCaseMapping ADD CONSTRAINT ScenarioCaseMapping_TestScenario_FK FOREIGN KEY ( TestScenarioID ) REFERENCES TestScenario ( TestScenarioID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerLaneDetails ADD CONSTRAINT SchedulerLaneDetails_AgentDetails_FK FOREIGN KEY ( AgentID ) REFERENCES AgentDetails ( AgentID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerLaneDetails ADD CONSTRAINT SchedulerLaneDetails_Scheduler_FK FOREIGN KEY ( ScheduleID ) REFERENCES Scheduler ( ScheduleID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_Scheduler_FK FOREIGN KEY ( ScheduleID ) REFERENCES Scheduler ( ScheduleID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SchedulerRunDetails ADD CONSTRAINT SchedulerRunDetails_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_AgentDetails_FK FOREIGN KEY ( AgentID ) REFERENCES AgentDetails ( AgentID ) ;

ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

ALTER TABLE Scheduler ADD CONSTRAINT Scheduler_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE Screen ADD CONSTRAINT Screen_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE Screen ADD CONSTRAINT Screen_AppFeature_FK FOREIGN KEY ( FeatureID ) REFERENCES AppFeature ( FeatureID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SuiteScenarioMapping ADD CONSTRAINT SuiteScenarioMapping_TestPlan_FKv1 FOREIGN KEY ( TestScenarioID ) REFERENCES TestScenario ( TestScenarioID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE SuiteScenarioMapping ADD CONSTRAINT SuiteScenarioMapping_TestSuite_FK FOREIGN KEY ( TestSuiteID ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE Task ADD CONSTRAINT TABLE_32_Lane_FK FOREIGN KEY ( LaneID ) REFERENCES SchedulerLaneDetails ( ScheduleLaneID ) ;

ALTER TABLE TaskResult ADD CONSTRAINT TABLE_33_Task_FK FOREIGN KEY ( TaskID ) REFERENCES Task ( TaskID ) ;

ALTER TABLE PlanSuiteMapping ADD CONSTRAINT TABLE_43_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE PlanSuiteMapping ADD CONSTRAINT TABLE_43_TestSuite_FK FOREIGN KEY ( TestSuiteID ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE LaneResults ADD CONSTRAINT TFWLaneResults_AgentDetails_FK FOREIGN KEY ( AgentID ) REFERENCES AgentDetails ( AgentID ) ;

ALTER TABLE LaneResults ADD CONSTRAINT TFWLaneResults_Lane_FK FOREIGN KEY ( ScheduleLaneID ) REFERENCES SchedulerLaneDetails ( ScheduleLaneID ) ;

ALTER TABLE TaskResult ADD CONSTRAINT TaskResult_LaneResults_FKv1 FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TaskResult ADD CONSTRAINT TaskResult_SchedulerLaneDetails_FK FOREIGN KEY ( LaneID ) REFERENCES SchedulerLaneDetails ( ScheduleLaneID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestCaseResult ADD CONSTRAINT TestCaseResult_SchedulerRunDetails_FK FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

ALTER TABLE TestCaseResult ADD CONSTRAINT TestCaseResult_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE TestCaseResult ADD CONSTRAINT TestCaseResult_TestScenario_FK FOREIGN KEY ( TestScenarioID ) REFERENCES TestScenario ( TestScenarioID ) ;

ALTER TABLE TestCase ADD CONSTRAINT TestCase_AppFeature_FK FOREIGN KEY ( FeatureID ) REFERENCES AppFeature ( FeatureID ) ;

ALTER TABLE TestCase ADD CONSTRAINT TestCase_AppFunctionality_FK FOREIGN KEY ( FunctionalID ) REFERENCES AppFunctionality ( FunctionalID ) ;

ALTER TABLE TestCase ADD CONSTRAINT TestCase_ConditionGroup_FK FOREIGN KEY ( ConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestCase ADD CONSTRAINT TestCase_Runner_FK FOREIGN KEY ( RunnerID ) REFERENCES Runner ( RunnerID ) ;

ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_ConditionGroup_FK FOREIGN KEY ( ConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_Conditions_FK FOREIGN KEY ( ConditionID ) REFERENCES Conditions ( ConditionID ) ;

ALTER TABLE TestConditionData ADD CONSTRAINT TestCondData_TestData_FK FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

ALTER TABLE TestData ADD CONSTRAINT TestData_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

ALTER TABLE TestParamData ADD CONSTRAINT TestParamData_ParamGroup_FKv1 FOREIGN KEY ( TestDataID ) REFERENCES TestData ( TestDataID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestPlanResult ADD CONSTRAINT TestPlanResult_SchedulerRunDetails_FK FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

ALTER TABLE TestPlanResult ADD CONSTRAINT TestPlanResult_TaskResult_FKv1 FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE TestPlanResult ADD CONSTRAINT TestPlanResult_Task_FK FOREIGN KEY ( TaskID ) REFERENCES Task ( TaskID ) ;

ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_ConditionGroup_FK FOREIGN KEY ( PreConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

ALTER TABLE TestPlan ADD CONSTRAINT TestPlan_ConditionGroup_FKv2 FOREIGN KEY ( PostConditionGroupID ) REFERENCES ConditionGroup ( ConditionGroupID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestScenarioResult ADD CONSTRAINT TestScenarioResult_SchedulerRunDetails_FK FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestScenarioResult ADD CONSTRAINT TestScenarioResult_TestScenario_FK FOREIGN KEY ( TestScenarioID ) REFERENCES TestScenario ( TestScenarioID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestScenarioResult ADD CONSTRAINT TestScenarioResult_TestSuite_FK FOREIGN KEY ( TestSuiteID ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE TestScenario ADD CONSTRAINT TestScenario_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestStepResult ADD CONSTRAINT TestStepResult_SchedulerRunDetails_FK FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestStepResult ADD CONSTRAINT TestStepResult_TestCaseResult_FKv1 FOREIGN KEY ( TestStepID ) REFERENCES TestStep ( TestStepID ) ;

ALTER TABLE TestStepResult ADD CONSTRAINT TestStepResult_TestCase_FK FOREIGN KEY ( TestCaseID ) REFERENCES TestCase ( TestCaseID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_Actions_FK FOREIGN KEY ( ActionID ) REFERENCES Actions ( ActionID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_ParamGroup FOREIGN KEY ( InputParamGroupID ) REFERENCES ParamGroup ( ParamGroupID ) ;

ALTER TABLE TestStep ADD CONSTRAINT TestStep_Runner_FKv1 FOREIGN KEY ( RunnerID ) REFERENCES Runner ( RunnerID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestSuiteResult ADD CONSTRAINT TestSuiteResult_SchedulerRunDetails_FK FOREIGN KEY ( TestRunID ) REFERENCES SchedulerRunDetails ( TestRunID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE TestSuiteResult ADD CONSTRAINT TestSuiteResult_TestPlanResult_FKv1 FOREIGN KEY ( TestSuiteID ) REFERENCES TestSuite ( TestSuiteID ) ;

ALTER TABLE TestSuiteResult ADD CONSTRAINT TestSuiteResult_TestPlan_FK FOREIGN KEY ( TestPlanID ) REFERENCES TestPlan ( TestPlanID ) ;

ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_APPLICATION_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ON
DELETE CASCADE ;

ALTER TABLE TestSuite ADD CONSTRAINT TestSuite_Application_FKv1 FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE UsersApplicationMapping ADD CONSTRAINT UsersApplicationMapping_Application_FK FOREIGN KEY ( AppID ) REFERENCES Application ( AppID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE UsersApplicationMapping ADD CONSTRAINT UsersApplicationMapping_Users_FK FOREIGN KEY ( USER_ID ) REFERENCES users ( USER_ID ) ;

ALTER TABLE user_roles ADD CONSTRAINT user_roles_Users_FK FOREIGN KEY ( USER_ID ) REFERENCES users ( USER_ID ) ;

-- 11-02-2014 -- stored procedure - scheduler_details(..)
DELIMITER //
create procedure scheduler_details(IN AppID INT(10))
BEGIN
        select s1.* from (select  s.SchedulerName, s.Scheduler_backupID as ScheduleID, @DateTIme as ScheduleTime, s.Frequency, s.Status, s.AppID, s.FailureCount,
        srd.Result, srd.StartDateTime, srd.EndDateTime, TIMESTAMPDIFF(SECOND, srd.StartDateTime, srd.EndDateTime) as DurationInSec, 
        tp.TestPlanID, tp.PlanName, td.TestDataID, td.TestDataDescription, ad.AgentName, ad.AgentID from Scheduler_backup s, 
        SchedulerRunDetails srd, TestPlan tp, TestData td, AgentDetails ad, Application a where s.TestPlanID=tp.TestPlanID and s.Scheduler_backupID=srd.ScheduleID and
        s.TestDataID=td.TestDataID and s.AgentID=ad.AgentID and s.AppID=a.AppID and s.AppID=AppID
        union (select  s11.SchedulerName, s11.ScheduleID, s11.ScheduleTime, s11.Frequency, s11.Status, s11.AppID, s11.FailureCount,
        srd11.Result, srd11.StartDateTime, srd11.EndDateTime, TIMESTAMPDIFF(SECOND, srd11.StartDateTime, srd11.EndDateTime) as DurationInSec11,
        tp11.TestPlanID, tp11.PlanName,
        td11.TestDataID, td11.TestDataDescription,
        ad11.AgentName, ad11.AgentID
        from Scheduler s11, SchedulerRunDetails srd11, TestPlan tp11, TestData td11, AgentDetails ad11, Application a11
        where s11.TestPlanID=tp11.TestPlanID and s11.TestDataID=td11.TestDataID and s11.AgentID=ad11.AgentID
        and s11.AppID=a11.AppID and s11.AppID=AppID)
        union (select s.SchedulerName, s.Scheduler_backupID  as ScheduleID, @DateTIme as ScheduleTime, s.Frequency, s.Status, s.AppID, s.FailureCount, 
        0 as Result, s.ScheduleTime as StartDateTime, s.ScheduleTime as EndDateTime, 0 as DurationInSec, 
        tp.TestPlanID, tp.PlanName, td.TestDataID, td.TestDataDescription, ad.AgentName, ad.AgentID
        from Scheduler_backup s, TestPlan tp, TestData td, AgentDetails ad
        where s.Scheduler_backupID not in (select distinct srd.ScheduleID from SchedulerRunDetails srd) 
        and s.AppID=AppID and s.TestPlanID=tp.TestPlanID and s.TestDataID=td.TestDataID and s.AgentID=ad.AgentID)) s1 
        group by s1.ScheduleID limit 30;
END //
DELIMITER ;

DELIMITER //
create procedure scheduler_details_running(IN AppID INT(10))
BEGIN
        select  s11.SchedulerName, s11.ScheduleID, s11.ScheduleTime, s11.Frequency, s11.Status, s11.AppID, s11.FailureCount,
        srd11.StartDateTime, tp11.TestPlanID, tp11.PlanName,
        td11.TestDataID, td11.TestDataDescription, ad11.AgentName, ad11.AgentID
        from Scheduler s11, SchedulerRunDetails srd11, TestPlan tp11, TestData td11, AgentDetails ad11, Application a11
        where s11.TestPlanID=tp11.TestPlanID and s11.TestDataID=td11.TestDataID and s11.AgentID=ad11.AgentID and s11.ScheduleID=srd11.ScheduleID
        and s11.AppID=a11.AppID and srd11.EndDateTime is null and s11.AppID=AppID;
END //
DELIMITER ;


DELIMITER //
create procedure scheduler_details_scheduled(IN AppID INT(10))
BEGIN        
        select  s11.SchedulerName, s11.ScheduleID, s11.ScheduleTime, s11.Frequency, s11.Status, s11.AppID, s11.FailureCount,
        tp11.TestPlanID, tp11.PlanName,
        td11.TestDataID, td11.TestDataDescription,
        ad11.AgentName, ad11.AgentID
        from Scheduler s11, TestPlan tp11, TestData td11, AgentDetails ad11, Application a11
        where s11.TestPlanID=tp11.TestPlanID and s11.TestDataID=td11.TestDataID and s11.AgentID=ad11.AgentID
        and s11.AppID=a11.AppID and s11.AppID=AppID;
END //
DELIMITER ;
commit;


DELIMITER //
create procedure scheduler_details_completed(IN AppID INT(10))
BEGIN
        select  s.SchedulerName, s.Scheduler_backupID as ScheduleID, s.ScheduleTime, s.Frequency, s.Status, s.AppID, s.FailureCount,
        srd.Result, srd.StartDateTime, srd.EndDateTime, TIMESTAMPDIFF(SECOND, srd.StartDateTime, srd.EndDateTime) as DurationInSec, 
        tp.TestPlanID, tp.PlanName, td.TestDataID, td.TestDataDescription, ad.AgentName, ad.AgentID from Scheduler_backup s, 
        SchedulerRunDetails srd, TestPlan tp, TestData td, AgentDetails ad, Application a where s.TestPlanID=tp.TestPlanID and s.Scheduler_backupID=srd.ScheduleID and
        s.TestDataID=td.TestDataID and s.AgentID=ad.AgentID and s.AppID=a.AppID and s.AppID=AppID;
END //
DELIMITER ;
commit;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            47
-- CREATE INDEX                             4
-- ALTER TABLE                            126
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                  32
-- WARNINGS                                 0
