
    create table "SYSTEM"."APPLICANTDETAILS"(
        "APPLICANTID" NUMBER(10) not null,
       "STATE" VARCHAR2(25),
       "DATEOFBIRTH" DATE,
       "TITLE" VARCHAR2(25),
       "FIRSTNAME" VARCHAR2(25),
       "LASTNAME" VARCHAR2(25),
       "MIDDLENAME" VARCHAR2(25),
       "APPLICATIONDATE" DATE,
       "DAYPHONE" VARCHAR2(25),
       "AVAILABILITY" VARCHAR2(25),
       "EXTENSION" VARCHAR2(25),
       "IMMIGRATION" VARCHAR2(25),
       "MARITALSTATUS" VARCHAR2(25),
       "EVENINGPHONE" VARCHAR2(25),
       "GENDER" VARCHAR2(25),
       "MOBILEPHONE" VARCHAR2(25),
       "ADDRESS" VARCHAR2(40),
       "EMAIL" VARCHAR2(30),
       "CITY" VARCHAR2(25),
       "ZIP" NUMBER(10),
       "QUALIFICATION" VARCHAR2(25),
       "SPECIALIZATION" VARCHAR2(25),
       "EXPERIENCE" NUMBER(10),
       "REFERENCE" VARCHAR2(25),
       "PRESENTSALARY" NUMBER(20),
       "EXPECTEDSALARY" NUMBER(20),
       "SECURITYNUMBER" NUMBER(20),
       "COMMENTS" VARCHAR2(40),
       "EMPID" NUMBER(10),
        constraint "AID2" primary key ("APPLICANTID")
    );

    alter table "SYSTEM"."APPLICANTDETAILS"
        add constraint "FEID1"
        foreign key ("EMPID")
        references "SYSTEM"."EMPLOYEEDETAILS"("EMPLOYEEID");
    create unique index "SYSTEM"."AID2" on "SYSTEM"."APPLICANTDETAILS"("APPLICANTID");