/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.struts;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 02-15-2011
 *
 * XDoclet definition:
 *
 * @struts.action path="/login" name="loginform" input="/login.jsp"
 *                validate="true"
 * @struts.action-forward name="failure" path="/index.jsp"
 * @struts.action-forward name="success" path="/index.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */
	LoginModel model;

	public LoginAction() {
		model = new LoginModel();
	}

	/**
	 * Method execute
	 *
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String key = "failure";
		boolean flag = false;
		LoginForm loginform = (LoginForm) form;
		String user = loginform.getUsername();
		String pass = loginform.getPassword();
		flag = model.isAuthenticate(user, pass);
		if (flag)
			return mapping.findForward("success");
		return mapping.findForward(key);
	}
}