/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.nit.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.nit.struts.Account;
import com.nit.struts.AccountNotFoundException;
import com.nit.struts.AccountService;
import com.nit.struts.DBException;

import edu.nit.struts.form.AccountForm;

/**
 * MyEclipse Struts Creation date: 03-12-2011
 *
 * XDoclet definition:
 *
 * @struts.action path="/account" name="accountForm" input="/account1.jsp"
 *                scope="request" validate="true"
 * @struts.action-exception key="error.dboperation.failed" path="/error.jsp"
 * @struts.action-exception key="error.search.failed" path="/noaccount.jsp"
 * @struts.action-forward name="failure" path="/noaccount.jsp"
 * @struts.action-forward name="error" path="/error.jsp"
 * @struts.action-forward name="success" path="/results.jsp"
 */
public class AccountAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 *
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	AccountService service;
	Account account;

	public AccountAction() {
		service = new AccountService();
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AccountForm accountForm = (AccountForm) form;
		String rkey = "success";
		int accno = accountForm.getAccno();
		try {
			try {
				account = service.getAccountDetails(accno);
			} catch (SQLException e) {
				e.printStackTrace();
			}
			if (account != null)
				request.setAttribute("account", account);
		} catch (DBException e) {
			System.out.println("DBException==>" + e.getClass().getName()
					+ "==>" + e.getMessage());
			rkey = "error";
		} catch (AccountNotFoundException e) {
			System.out.println("AccountNotFoundException==>"
					+ e.getClass().getName() + "==>" + e.getMessage());
			rkey = "failure";
		}
		ActionForward forward = mapping.findForward(rkey);
		return forward;
	}
}