package com.nit.struts;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import org.apache.struts.action.ActionForm;

/**
 * MyEclipse Struts
 * Creation date: 03-12-2011
 *
 * XDoclet definition:
 * @struts.form name="accountform"
 */
public class AccountForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	/** accno property */
	private Integer accno;

	/*
	 * Generated Methods
	 */

	/**
	 * Returns the accno.
	 * @return Integer
	 */
	public Integer getAccno() {
		return accno;
	}

	/**
	 * Set the accno.
	 * @param accno The accno to set
	 */
	public void setAccno(Integer accno) {
		this.accno = accno;
	}
}