/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package edu.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import edu.form.StudentForm;

/**
 * MyEclipse Struts Creation date: 01-01-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/StudentAction" name="StudentForm" input="student.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="failure" path="/failure.jsp"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class StudentAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentForm studentForm = (StudentForm) form;
		if (!"N@IT".equalsIgnoreCase(studentForm.getStudentName())) {
			return mapping.findForward("failure");
		}
		return mapping.findForward("success");
	}
}